# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2c5c5ef18e9bcca4b44aaa670dbf8cf9884e50e017d39862a6699bc6a75cc4006027dc696d75d878a582b7e7dfe83c7bcc7a66ebe082d00b9d302801d32d72a

test:
  secret_key_base: 95039f4e4b2745b9f4b71bc454d45bb5cdef1bc58322ede17518c682744db5985d3480accc61f0ed885663f36dc934d2bc7234edc23346c9f8364ebfbafecc64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
